#!/usr/bin/env python3
"""Generate deterministic CoreDNS and Squid policy from a validated F1.2c plan."""

from __future__ import annotations

import argparse
import pathlib
import sys
from typing import Any

REPOSITORY_ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPOSITORY_ROOT))

from scripts.compile_network_policy import PolicyError, load_and_validate


def _token(value: str) -> str:
    return value.replace("-", "_").replace(".", "_")


def generate_hosts(plan: dict[str, Any], interface: str) -> str:
    lines = [
        f"{record['ipv4']} {record['name']}"
        for record in plan["_validated"]["records"]
        if interface in record["visible_to_interfaces"]
    ]
    return "\n".join(sorted(lines)) + ("\n" if lines else "")


def generate_coredns(plan: dict[str, Any]) -> str:
    blocks: list[str] = []
    for sandbox in plan["_validated"]["sandboxes"]:
        if sandbox["egress_profile"] == "none":
            continue
        interface = sandbox["interface"]
        gateway = sandbox["gateway_ipv4"]
        blocks.extend(
            [
                ".:53 {",
                f"    bind {gateway}",
                f"    hosts /etc/cloud-platform/dns/{interface}.hosts {{",
                "        ttl 30",
                "        no_reverse",
                "        fallthrough",
                "    }",
                "    forward . /etc/resolv.conf {",
                "        policy sequential",
                "        max_fails 1",
                "    }",
                "    cache 30",
                "    errors",
                "}",
                "",
            ]
        )
    return "\n".join(blocks)


def generate_squid(plan: dict[str, Any]) -> str:
    sandboxes = [
        item
        for item in plan["_validated"]["sandboxes"]
        if item["egress_profile"] != "none"
    ]
    destinations = plan["_validated"]["destinations"]
    lines = [
        "# Generated by CODEX-EXECUTION-MISSION-001; direct edits are forbidden.",
        "visible_hostname cloud-platform-egress-dev",
        "cache deny all",
        "via off",
        "forwarded_for delete",
        "request_header_access X-Forwarded-For deny all",
        "acl CONNECT method CONNECT",
        "acl Safe_ports port 80 443",
        "acl SSL_ports port 443",
        "acl protected_dst dst 10.0.0.0/8 100.64.0.0/10 169.254.0.0/16 172.16.0.0/12 192.168.0.0/16",
        "acl protected_dst6 dst ::1/128 fc00::/7 fe80::/10",
    ]
    for sandbox in sandboxes:
        lines.append(f"http_port {sandbox['gateway_ipv4']}:3128")
        lines.append(f"acl source_{_token(sandbox['interface'])} src {sandbox['subnet_ipv4']}")
    for destination in destinations:
        name = _token(destination["destination_id"])
        lines.append(f"acl destination_{name} dstdomain {destination['hostname']}")
        lines.append(
            f"acl destination_ports_{name} port "
            + " ".join(str(port) for port in sorted(destination["ports"]))
        )
    lines.extend(
        [
            "http_access deny !Safe_ports",
            "http_access deny CONNECT !SSL_ports",
            "http_access deny protected_dst",
            "http_access deny protected_dst6",
        ]
    )
    for sandbox in sandboxes:
        source = _token(sandbox["interface"])
        profile = sandbox["egress_profile"]
        for destination in destinations:
            if profile not in destination["profiles"]:
                continue
            name = _token(destination["destination_id"])
            lines.append(
                f"http_access allow source_{source} destination_{name} destination_ports_{name}"
            )
    lines.extend(["http_access deny all", "access_log stdio:/var/log/squid/access.log", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("policy", type=pathlib.Path)
    parser.add_argument(
        "--component",
        required=True,
        choices=("coredns", "squid", "hosts"),
    )
    parser.add_argument("--interface")
    args = parser.parse_args()
    try:
        plan = load_and_validate(args.policy)
        if args.component == "coredns":
            output = generate_coredns(plan)
        elif args.component == "squid":
            output = generate_squid(plan)
        else:
            if not args.interface:
                raise PolicyError("--interface is required for hosts")
            interfaces = {item["interface"] for item in plan["_validated"]["sandboxes"]}
            if args.interface not in interfaces:
                raise PolicyError("hosts interface is not declared by the policy")
            output = generate_hosts(plan, args.interface)
    except PolicyError as exc:
        print(f"NETWORK_SERVICES_REFUSED: {exc}", file=sys.stderr)
        return 2
    sys.stdout.write(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
