#!/usr/bin/env python3
"""Generate deterministic CoreDNS and Squid policy from a validated F1.2c plan."""

from __future__ import annotations

import argparse
import pathlib
import sys
from typing import Any

REPOSITORY_ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPOSITORY_ROOT))

from scripts.compile_network_policy import PolicyError, load_and_validate


def _token(value: str) -> str:
    return value.replace("-", "_").replace(".", "_")


def generate_hosts(plan: dict[str, Any], interface: str) -> str:
    lines = [
        f"{record['ipv4']} {record['name']}"
        for record in plan["_validated"]["records"]
        if interface in record["visible_to_interfaces"]
    ]
    return "\n".join(sorted(lines)) + ("\n" if lines else "")


def _sandbox(plan: dict[str, Any], interface: str) -> dict[str, Any]:
    matches = [
        item for item in plan["_validated"]["sandboxes"] if item["interface"] == interface
    ]
    if len(matches) != 1:
        raise PolicyError("service interface is not declared by the policy")
    if matches[0]["egress_profile"] == "none":
        raise PolicyError("none profile has no DNS or proxy service")
    return matches[0]


def generate_coredns(plan: dict[str, Any], interface: str) -> str:
    _sandbox(plan, interface)
    return "\n".join(
        [
            "dev.internal:53 {",
            "    bind 0.0.0.0",
            "    hosts /etc/coredns/records.hosts {",
            "        ttl 30",
            "        no_reverse",
            "    }",
            "    errors",
            "}",
            "",
            ".:53 {",
            "    bind 0.0.0.0",
            "    forward . 1.1.1.1 1.0.0.1 {",
            "        policy sequential",
            "        max_fails 1",
            "    }",
            "    cache 30",
            "    errors",
            "}",
            "",
        ]
    )


def generate_squid(plan: dict[str, Any], interface: str) -> str:
    sandbox = _sandbox(plan, interface)
    destinations = plan["_validated"]["destinations"]
    lines = [
        "# Generated by CODEX-EXECUTION-MISSION-001; direct edits are forbidden.",
        f"visible_hostname cloud-platform-egress-{sandbox['egress_profile']}",
        "cache deny all",
        "via off",
        "forwarded_for delete",
        "request_header_access X-Forwarded-For deny all",
        "acl CONNECT method CONNECT",
        "acl Safe_ports port 80 443",
        "acl SSL_ports port 443",
        "acl protected_dst dst 10.0.0.0/8 100.64.0.0/10 169.254.0.0/16 172.16.0.0/12 192.168.0.0/16",
        "acl protected_dst6 dst ::1/128 fc00::/7 fe80::/10",
        "dns_nameservers 1.1.1.1 1.0.0.1",
    ]
    lines.append("http_port 0.0.0.0:3128")
    lines.append(f"acl scope_source src {sandbox['subnet_ipv4']}")
    for destination in destinations:
        name = _token(destination["destination_id"])
        lines.append(f"acl destination_{name} dstdomain {destination['hostname']}")
        lines.append(
            f"acl destination_ports_{name} port "
            + " ".join(str(port) for port in sorted(destination["ports"]))
        )
    lines.extend(
        [
            "http_access deny !Safe_ports",
            "http_access deny CONNECT !SSL_ports",
            "http_access deny protected_dst",
            "http_access deny protected_dst6",
        ]
    )
    profile = sandbox["egress_profile"]
    for destination in destinations:
        if profile not in destination["profiles"]:
            continue
        name = _token(destination["destination_id"])
        lines.append(
            f"http_access allow scope_source destination_{name} destination_ports_{name}"
        )
    lines.extend(["http_access deny all", "access_log stdio:/var/log/squid/access.log", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("policy", type=pathlib.Path)
    parser.add_argument(
        "--component",
        required=True,
        choices=("coredns", "squid", "hosts"),
    )
    parser.add_argument("--interface")
    args = parser.parse_args()
    try:
        plan = load_and_validate(args.policy)
        if not args.interface:
            raise PolicyError("--interface is required for scoped service output")
        if args.component == "coredns":
            output = generate_coredns(plan, args.interface)
        elif args.component == "squid":
            output = generate_squid(plan, args.interface)
        else:
            _sandbox(plan, args.interface)
            output = generate_hosts(plan, args.interface)
    except PolicyError as exc:
        print(f"NETWORK_SERVICES_REFUSED: {exc}", file=sys.stderr)
        return 2
    sys.stdout.write(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
